### ISSUE TITLE
Koodikatselmus 1

### ISSUE THREAD

**Issue by ghost** [Footless/MealPlanner#1]
_Projekti ladattu 31.12.2016 15:04_

# Yleistä
Projektion dokumentaatio on laaja ja selkeä. Erityisesti luokkakaaviot ovat kattavia. Etusivun tiivistelmästä voisi siirtää yksityiskohtia tarkempaan aihekuvaukseen. Projektin testit menevät kaikki onnistuneesti läpi. Testit ovat melko kattavia laajuudeltaan. Triviaalien testien määrä on myös niiden tekemisen puuduttavuuden huomioiden positiivista. Checkstyle-testi antoi 47 virhettä lataamassani versiossa. PIT-kattavuus oli hyvä. PIT kannattaa kuitenkin konfiguroida jättämään käyttöliittymäluokat huomioimatta. Testiluokkien koodi kaipaa hieman siivousta. Useisiin luokkiin ja muuttujiin olisi mahdollista lisätä final-avainsana.

Kokonaisuudessaan kyseessä on aihealueltaan hyvin mielenkiintoinen projekti jonka toteutus on jo nyt erittäin lupaavassa vaiheessa.

# Käyttöliittymä
**Huomiot koskevat vain toteutettuja osia.** Tekstin formatointi ja numeroiden pyöristys ovat ominaisuuksia joiden puute on tällä hetkellä ilmeisin. Käyttöliittymä ei näytä esimerkiksi ääkkösiä oikein
tällä hetkellä. Toisaalta taas tieto siitä että ateria sisältää 402.18059273422557 kilokaloria voi olla jopa liian tarkka monelle käyttäjälle. Tähän liittyen ravintoarvojen yksikkö ilmoitetaan tällä hetkellä kahdesti. Laskurin tulossivulta ei myöskään ole tällä hetkellä mahdollisuutta palata laskuriin ohjelmaa uudelleenkäynnistämättä.

Koodin osalta käyttöliittymä on melko siististi toteutettu. Ohjeistuksen mukaiset pituudet rikkoutuvat paikoittain (esim. UserInterface-luokan createMainIngredientCard-metodi) mutta tämä on mielestäni näissä tapauksissa perusteltua. Toki esim. yksittäisten komponenttien alustuksesta voisi tehdä omat metodinsa. Tapahtumakäsittelijöiden periminen omiksi luokikseen on erittäin toimiva ratkaisu joka helpottaa suuresti luettavuutta.

Swingin konfiguroiminen natiivikomponentteja matkivaksi voi auttaa käyttöliittymän ulkoasun parantamisesssa (ajoympäristöjen yhtenäisyyden kustannuksella). Tämä onnistuu seuraavalla loitsulla (oleellisten importtien kera) ennen käyttöliittymän alustusta:
``` 
try {

 UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());

} catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException e) {} 
``` 

# Logiikka
Virheiden hallinta kaipaa parannusta. Tällä hetkellä virhetilanteista ei ilmoiteta käyttäjälle komentoriviä lukuunottamatta ja esimerkiksi tiedoston puuttuessa ohjelma kaatuu käynnistysvaiheessa.

Ateriakokonaisuuksien rakentaminen ei myöskään toimi kovin hyvin. Esimerkkejä kokonaisuuksien osista joita ohjelma suositteli:

_Bearnaisekastike: -8.0gr_
_dump: -Infinitygr_

Ravintoarvoja tietty ateriakokonaisuus sisälsi mm. _Kilokalorit: NaNkcal_. Virheellisiä kokonaisuuksia näytti syntyvän erityisesti säätimien ääriarvoilla.

Ohjelman logiikan koodi vaikuttaa pääosin järkevältä jo käyttöliittymäkoodin osuudessa mainitut huomiot poislukien. Koodi on laadultaan hyvää ja siistiä eikä mielestäni huomatettavaa (bugeja lukuunottamatta) juuri ole. Suurehko osa logiikkakoodista onkin ilmeisesti vielä toteuttamatta joten mainitut epäkohdat ovat ymmärrettäviä. Koodin luettavuus on kuitenkin jo nyt hyvällä tasolla. Oletuslisenssi-tekstipätkät lienee syytä kuitenkin siivota pois.

**Comment by quantti** [comment]
Iso kiitos kattavasta palautteesta. Osa noista onkin jo tässä vaiheessa korjattu, mutta esim. ääkkösiin liittyvä huomio oli todella arvokas, koska omalla koneellani ääkköset näkyvät aivan normaalisti. Pitää tutkia missä vaiheessa jotain vaihtuu.
