### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by viltuul** [Footless/MealPlanner#2]
koodi ladatttu 08.01.17 klo 13.00

Päälisinpuolin koodi näyttää eheältä ja ohjelma toimii. Siellä täällä löytyy muutama käyttämätön importti, jotka todennäköisesti kannattaa poistaa ennen demotilaisuutta. Metodit ovat pidetty keskimäärin lyhyinä ja yksinkertaisina. Joistain luokista kuitenkin löytyy pitkiä metodeja, (varsinkin sellaiset jotka sisältävät monia if ja if else lausekkeita) joita pystyisi jakamaan pienempiin private metodeihin. Tällä ei toiminnallisuuden kannalta ole etuja mutta koodinluku ja refaktorointi helpottuu. Komponenteista, jotka eivät vielä toimi, ilmoitetaan niitä kokeillessa, mikä on mielestäni hyvä idea. Kattavat testit sekä mutaatiot hoidettu.

Koodi on mielestäni erinomaista ja aion hyödyntää jotain osa-alueita omassa ohjelmassani. 

(En tiedä onko paha, mutta metodit ja attribuutit on kirjoitettu englanniksi ja javadoc suomeksi. Muistelen, että koodinkirjoituksessa tulisi välttää useampaa kieltä.)

**Comment by quantti** [comment]
Kiitos palautteesta, tsekkasin javadocit ja on ihan ok noin. Siistimistä on, huomasin vasta nyt miten paljon...
